### ISSUE TITLE
GreenCoffeeTest has only constructors taking scenarios

### ISSUE THREAD

**Issue by getsadzeg** [mauriciotogneri/green-coffee#1]
When I run a test it says:

`junit.framework.AssertionFailedError: Class has no public constructor TestCase(String name) or TestCase()`

So it seems GreenCoffeeTest has only constructors taking scenarios.

What can I do @mauriciotogneri ?

[StackOverflow Link](http://stackoverflow.com/questions/39518848/class-has-no-public-constructor-testcasestring-name-or-testcase-while-runnin)

**Comment by mauriciotogneri** [comment]
Hi @getsadzeg, sorry for the late response. Due to the fact that tests in GreenCoffee require:

@RunWith(Parameterized.class)

The static method annotated with @Parameters must return a list of something. In the examples in the documentation I simply return a list of scenarios, that's why the constructor must take a single Scenario as a parameter.

However, you can create a class that encapsulates the scenario and other objects that you may need to pass to the constructor. So you will get something like this:

public MembersFeatureTest(TestParameters testParameters) {
    super(testParameters.scenario());
}

@Parameters
public static Iterable<TestParameters> parameters() throws IOException {
        return // create the list of TestParameters
}

Let me know if you encounter any issues.

**Comment by getsadzeg** [comment]
Okay got it, but why does the error appear? :disappointed:
