### ISSUE TITLE
Sharing steps between tests

### ISSUE THREAD

**Issue by chris-gunawardena** [mauriciotogneri/green-coffee#13]
We have common steps like "Given I'm logged in" that needs to be shared between tests, what the best way to do this? I already tried extending off a CommonSteps class that extends from GreenCoffeeSteps but it's not inheriting the step definitions.

**Comment by mauriciotogneri** [comment]
Hi, have a look at this example:

https://github.com/vndly/green-coffee-example/tree/master/app/src/androidTest/java/com/mauriciotogneri/greencoffeeexample/test

The idea is to have one class that handle all the steps related to one screen/unit of functionality/feature, etc. (e.g. https://github.com/vndly/green-coffee-example/blob/master/app/src/androidTest/java/com/mauriciotogneri/greencoffeeexample/test/steps/LoginSteps.java)

Then you use the steps in the class that extends from GreenCoffeeTest (e.g. https://github.com/vndly/green-coffee-example/blob/master/app/src/androidTest/java/com/mauriciotogneri/greencoffeeexample/test/features/LoginFeatureTest.java#L48)

Like that you can include a set of common steps in different features easily.

I hope that solves your problem and let me know otherwise.

**Comment by chris-gunawardena** [comment]
Thanks Mauricio, didn't realise start() method can take multiple arguments.

**Comment by mauriciotogneri** [comment]
You are welcome! Let me know if you have some ideas or features to improve the library.
