### ISSUE TITLE
GreenCoffeeConfig.concreteStep does not convert variables in Node argument, only in text. 

### ISSUE THREAD

**Issue by mikegr** [mauriciotogneri/green-coffee#4]
Here is an example of a scenario outline
```
Scenario Outline: Simplified test case
  Given I have a Model with:
        | alias      |  <alias>    |
        | attribute  | <attribute> |
  When I test
  Then I check for output <output>
  Examples:
    | id | alias  | attribute     | output |
    |  1 | Mr X   | awesome       | 0      |
    |  2 | Mrs Y  | very awesome  | 1      |
```
&lt;output&gt; is replaced, but &lt;alias&gt; and &lt;attribute&gt; are not.

**Comment by mauriciotogneri** [comment]
Hi @mikegr,

Indeed, when you run such a test, the <output> will be filled but not the <alias> and <attribute>. In order to parse the Gherkin files I'm using the official [Java parser] (https://github.com/cucumber/gherkin-java) and it's not returning the values filled so I guess you should open a ticket on their side in order to fix the bug.

However, I'm not sure DataTables are meant to be used with examples. I couldn't find an example on Internet of this kind of usage. I didn't see in the official documentation anything saying if this is allowed/forbidden. So I have no idea if it's actually possible.
